### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Nemisor** [apsun/TumblrAdAway#1]
I would be immensely grateful if this could be enhanced to block the "sponsored posts" as well. Nothing else can do this on mobile, so it would be greatly appreciated. Thanks!

**Comment by apsun** [comment]
Huh? It should be blocking the sponsored posts. Can you post a screenshot of the post in question? A logcat dump would also be helpful:

`adb logcat -s "TumblrAdAway"`

**Comment by Nemisor** [comment]
Actually, never mind. It is blocking them now. An older version wasn't
doing it but just confirmed it is working. Thanks!

**Comment by apsun** [comment]
Ah, okay. If it starts acting up again feel free to re-open this issue, I haven't updated the module in quite a few Tumblr versions since their ad loading code hasn't changed, so if the problem occurs again it's likely a bug in the module.

**Comment by Nemisor** [comment]
Thanks again! I'm also testing the Soundcloud module. Seems good so far...
can't stand those ads!
