### ISSUE TITLE
Incompatible with JellyBean Xposed?

### ISSUE THREAD

**Issue by oroboros** [apsun/TumblrAdAway#11]
When I try to update the latest 1.7 version, Xposed says it's incompatible (or not valid APK). Maybe it's because I'm running v58 on JellyBean? Can you help, please?

**Comment by apsun** [comment]
Ah, in 1.7 I accidentally changed the min SDK version of the module to 19 (KitKat). Sorry about that. I've reverted it to 4 in 0b2cd1d753d4488c4330e98a7debce6ffa130817 (1.7.1).
