### ISSUE TITLE
希望可以加入视频缓存功能

### ISSUE THREAD

**Issue by hetykai** [apsun/TumblrAdAway#16]
官方的app貌似没有视频缓存，每次点击同一个都得重新缓冲，中国大陆地区网络很差，每次加载视频都很慢。所以希望可以加入视频缓存功能，点击一个视频如果本地有缓存，优先播放本地缓存。

**Comment by EnderDragonEP** [comment]
这个插件主要的功能是阻挡浏览Tumblr时出现的会广告，如果想要其他功能可能还要找。

The main goal of this module is to block ads when browsing on Tumblr, if you want other features you might have to search for it.

**Comment by hetykai** [comment]
Ok, thanks.
