### ISSUE TITLE
Base update 

### ISSUE THREAD

**Issue by hakankocyigit** [apsun/TumblrAdAway#5]
Tumblr 6.9.0.x come soon? Please

**Comment by apsun** [comment]
The module already works fine on 6.9.0, I only update it when it stops functioning (which hasn't happened in a long time). What issues are you having?

**Comment by hakankocyigit** [comment]
Okay then. I load the module now, but I've seen the last update 6.3.0 support. I thought that's why tumblr support for new versions. We more try. If you are working with now on tumblr version is no problem. Does it work smoothly Tumblr module in beta? (I'm sorry not good english)

**Comment by apsun** [comment]
I can't guarantee that it works on beta versions, since I am not in the beta program. If the module ever stops working on a new version, just create a new issue and I'll fix it ASAP.
