### ISSUE TITLE
Android 4.4.2/GT-7100: Not blocking? Tumblr 7.5.0.14

### ISSUE THREAD

**Issue by Rbagman** [apsun/TumblrAdAway#8]
I saw this Xposed mod and installed Tumblr app. But I see sponsored posts. Are these the ads or do they have banner ads too?

**Comment by apsun** [comment]
Looks like they changed the Tumblr code. I'll try to fix it, but I can't test it myself since I don't have a device with Xposed installed at the moment.

Can you post a logcat dump?

**Comment by apsun** [comment]
Hm, I just tested the module and it works on the latest version of the app. Closing as not reproducible.
